[package]
name = "booltable"
authors = ["Jawad Ahmed <jawad.w.ahmed@gmail.com>"]
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
logos = "0.12"
ariadne = "0.1"
derive_more = "0.99"
